sudo: required
dist: trusty

git:
  submodules: false

addons:
  chrome: stable
  hosts:
    - www.pokemon-friends.com.local
  ssh_known_hosts:
    - github.com
    - deploy.eu2.frbit.com

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/vendor
    - $HOME/node_modules

stages:
  - test
  - coverage
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = master)
  - tag

jobs:
  fast_finish: true
  include:
  - stage: test
    name: pokemon-friends-com/www PHP Standard PSR12
    language: php
    php: 7.3
    env:
      - CODECLIMATE=off
      - APP_ENV=testing
    before_install:
      - printf "\n" | pecl install imagick
    install:
      - composer install -o --no-interaction --prefer-dist --no-suggest
    script:
      - vendor/bin/phpcs --standard=PSR12 app
      - vendor/bin/phpcs --standard=PSR12 components
      - vendor/bin/phpcs --standard=PSR12 database/factories
      - vendor/bin/phpcs --standard=PSR12 routes
      - vendor/bin/phpcs --standard=PSR12 tests --extensions=php
  - stage: test
    name: pokemon-friends-com/www PHP
    language: php
    php: 7.3
    env:
      - CODECLIMATE=off
      - APP_ENV=testing
    before_install:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
        fi
      - printf "\n" | pecl install imagick
      - nvm install
      - nvm use
    install:
      - composer install -o --no-interaction --prefer-dist --no-suggest
      - npm install
    before_script:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          ./cc-test-reporter before-build
        fi
      - npm run dev
      - php artisan elfinder:publish
    script:
      - vendor/bin/phpunit
      - php artisan test:check-coverage ./coverage/clover.xml 80
    after_script:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          php artisan file:cloud:push coverage/clover.xml coverages/${TRAVIS_COMMIT}/clover.xml
        fi
  - stage: test
    name: pokemon-friends-com/www JS&TS
    language: php
    php: 7.3
    env:
      - CODECLIMATE=off
      - APP_ENV=testing
    before_install:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
        fi
      - printf "\n" | pecl install imagick
      - nvm install
      - nvm use
    install:
      - composer install -o --no-interaction --prefer-dist --no-suggest
      - npm install
    before_script:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          ./cc-test-reporter before-build
        fi
      - npm run dev
    script:
      - npm test
    after_script:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          php artisan file:cloud:push coverage/lcov.info coverages/${TRAVIS_COMMIT}/lcov.info
        fi
  - stage: coverage
    name: Send codeclimate coverage
    language: php
    php: 7.3
    env:
      - CODECLIMATE=off
      - APP_ENV=testing
    before_install:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
        fi
      - printf "\n" | pecl install imagick
      - mkdir coverage
    install:
      - composer install -o --no-interaction --prefer-dist --no-suggest
    script:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          php artisan file:cloud:get coverages/${TRAVIS_COMMIT}/clover.xml coverage/clover.xml
          php artisan file:cloud:get coverages/${TRAVIS_COMMIT}/lcov.info coverage/lcov.info
          ./cc-test-reporter format-coverage -t clover -o coverage/codeclimate.php.json coverage/clover.xml
          ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.js.json coverage/lcov.info
          ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
          ./cc-test-reporter upload-coverage
        fi
    after_script:
      - |
        if [[ "$CODECLIMATE" = "on" ]]; then
          php artisan file:cloud:rm coverages/${TRAVIS_COMMIT}/clover.xml
          php artisan file:cloud:rm coverages/${TRAVIS_COMMIT}/lcov.info
        fi
  - stage: deploy
    name: pokemon-friends-com/www
    language: php
    php: 7.3
    before_install:
      - printf "\n" | pecl install imagick
      - nvm install
      - nvm use
    install:
      - cp .env.example .env
      - composer install -o --no-interaction --prefer-dist --no-suggest
      - npm install
      - php artisan elfinder:publish
    script:
      - npm run production
    before_deploy:
      - chmod 777 bin/*.sh
      - bash bin/decrypt_travis_enc_files.sh
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/deploy_rsa
      - ssh-add /tmp/deploy_rsa
      - php artisan asset-cdn:sync
    deploy:
      - provider: script
        skip_cleanup: true
        script: bash bin/push_to_fortrabbit.sh
        on:
          branch: master
  - stage: tag
    if: (NOT type IN (pull_request)) AND (branch = develop)
    name: pokemon-friends-com/www tag staging
    language: generic
    before_install:
      - git config --global user.email "builds@travis-ci.com"
      - git config --global user.name "Travis CI"
    script:
      - git tag staging -f -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
      - git push -f -q https://$GITHUBKEY@github.com/pokemon-friends-com/www.git staging
  - stage: tag
    if: (NOT type IN (pull_request)) AND (branch = master)
    name: pokemon-friends-com/www tag master
    language: generic
    before_install:
      - git config --global user.email "builds@travis-ci.com"
      - git config --global user.name "Travis CI"
    install:
      - cp .env.example .env
      - export $(grep -v '^#' .env | xargs -0)
    script:
      - git tag ${APP_VERSION} -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
      - git push -q https://$GITHUBKEY@github.com/pokemon-friends-com/www.git ${APP_VERSION}
