sudo: required
dist: trusty

git:
  submodules: false

addons:
  chrome: stable
  hosts:
    - www.pokemon-friends.com.local
  ssh_known_hosts:
    - github.com
    - deploy.eu2.frbit.com

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/vendor
    - $HOME/node_modules

stages:
  - test
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = master)
  - tag

jobs:
  fast_finish: true
  include:
  - stage: test
    name: PHP standard PSR12
    language: php
    php: 7.3
    env:
      - CODECLIMATE=off
      - APP_ENV=testing
    before_install:
      - printf "\n" | pecl install imagick
    install:
      - composer install -o --no-interaction --prefer-dist --no-suggest
    script:
      - vendor/bin/phpcs --standard=PSR12 app
      - vendor/bin/phpcs --standard=PSR12 components
      - vendor/bin/phpcs --standard=PSR12 database/factories
      - vendor/bin/phpcs --standard=PSR12 routes
      - vendor/bin/phpcs --standard=PSR12 tests --extensions=php
      - vendor/bin/phpstan analyse -l 0 app components tests
  - stage: test
    name: PHP tests
    language: php
    php: 7.3
    env:
      - APP_ENV=testing
    before_install:
      - printf "\n" | pecl install imagick
      - nvm install
      - nvm use
    install:
      - composer install -o --no-interaction --prefer-dist --no-suggest
      - npm install
    before_script:
      - npm run dev
      - php artisan elfinder:publish
    script:
      - vendor/bin/phpunit
    after_script:
      - bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml
  - stage: test
    name: JS tests
    language: php
    php: 7.3
    env:
      - APP_ENV=testing
    before_install:
      - printf "\n" | pecl install imagick
      - nvm install
      - nvm use
    install:
      - composer install -o --no-interaction --prefer-dist --no-suggest
      - npm install
    before_script:
      - npm run dev
    script:
      - npm test
    after_script:
      - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
  - stage: deploy
    name: pokemon-friends-com/www
    language: php
    php: 7.3
    before_install:
      - printf "\n" | pecl install imagick
      - nvm install
      - nvm use
    install:
      - cp .env.example .env
      - composer install -o --no-interaction --prefer-dist --no-suggest
      - npm install
      - php artisan elfinder:publish
    script:
      - npm run production
    before_deploy:
      - chmod 777 bin/*.sh
      - bash bin/decrypt_travis_enc_files.sh
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/deploy_rsa
      - ssh-add /tmp/deploy_rsa
      - APP_ENV=production php artisan asset-cdn:sync --env=production
    deploy:
      - provider: script
        skip_cleanup: true
        script: bash bin/push_to_fortrabbit.sh
        on:
          branch: master
  - stage: tag
    if: (NOT type IN (pull_request)) AND (branch = master)
    name: pokemon-friends-com/www tag master
    language: generic
    before_install:
      - git config --global user.email "builds@travis-ci.com"
      - git config --global user.name "Travis CI"
    install:
      - cp .env.example .env
      - export $(grep -v '^#' .env | xargs -0)
    script:
      - git tag ${APP_TAG} -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
      - git push -q https://$GITHUBKEY@github.com/pokemon-friends-com/www.git ${APP_TAG}
