sudo: required
dist: trusty
language: php

git:
  submodules: false

addons:
  chrome: stable
  hosts:
    - www.obsession.city.local
  ssh_known_hosts:
    - deploy.eu2.frbit.com
    - github.com

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor
    - node_modules

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - CODECLIMATE=on
        - APP_ENV=testing
    - php: 7.4
      env:
        - CODECLIMATE=off
        - APP_ENV=testing
    - php: nightly
      env:
        - CODECLIMATE=off
        - APP_ENV=testing
  allow_failures:
    - php: nightly
    - php: 7.4

before_install:
  - chmod 777 scripts/*.sh
  - bash scripts/decrypt_travis_enc_files.sh
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git submodule update --init resources/clip
  - git submodule update --init resources/gameforest
  - git submodule update --init resources/pages
  - printf "\n" | pecl install imagick
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
    fi
  - nvm install
  - nvm use
  - npm install grunt-cli@1.3.2 -g

install:
  - travis_retry composer install -o --no-interaction --prefer-dist --no-suggest
  - travis_retry npm install

before_script:
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      ./cc-test-reporter before-build
    fi
  - travis_retry npm run gameforest
  - travis_retry npm run pages
  - bash scripts/prepare_pages_assets.sh
  - travis_retry npm run prod

script:
  - vendor/bin/phpunit

after_script:
  - |
    if [[ "$CODECLIMATE" = "on" ]]; then
      ./cc-test-reporter format-coverage -t clover -o coverage/codeclimate.php.json coverage/clover.xml
      ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 1
      ./cc-test-reporter upload-coverage
    fi
