version: '3.7'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  elasticsearch:
    driver: local

services:

  ### Workspace Utilities Container ###########################

  workspace:
    image: abenevaut/laradock-workspace:0.1.2
    volumes:
      - ${DOCKER_PROJECT_PATH}:/var/www:cached
    extra_hosts:
      - "dockerhost:10.0.75.1"
    ports:
      - "${DOCKER_WORKSPACE_PUBLIC_PORT}:22"
    tty: true
    environment:
      - PHP_IDE_CONFIG="serverName=${APP_NAME}"
    networks:
      - frontend
      - backend

  ### PHP-FPM Container #######################################

  php-fpm:
    image: abenevaut/laradock-php-fpm:0.1.2
    volumes:
      - ./laradock/php-fpm/php${DOCKER_PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${DOCKER_PROJECT_PATH}:/var/www:cached
    expose:
      - "${DOCKER_PHPFPM_PORT}"
    extra_hosts:
      - "dockerhost:10.0.75.1"
    environment:
      - PHP_IDE_CONFIG="serverName=${APP_NAME}"
      - DOCKER_HOST=tcp://docker-in-docker:2375
      - FAKETIME=-0
    depends_on:
      - workspace
    networks:
      - backend

  ### PHP Worker Container #####################################

  php-worker:
    image: abenevaut/laradock-php-worker:0.1.2
    volumes:
      - ${DOCKER_PROJECT_PATH}:/var/www:cached
      - ${DOCKER_STORAGE_PATH}/php-worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:10.0.75.1"
    networks:
      - backend

  ### Apache Server Container #################################

  apache2:
    image: abenevaut/laradock-apache2:0.1.2
    volumes:
      - ${DOCKER_PROJECT_PATH}:/var/www:cached
      - ${DOCKER_STORAGE_PATH}/apache2/logs:/var/log/apache2
      - ${DOCKER_STORAGE_PATH}/apache2/sites:/etc/apache2/sites-available
    ports:
      - "${DOCKER_APACHE_PUBLIC_HTTP_PORT}:80"
      - "${DOCKER_APACHE_PUBLIC_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  ### MySQL Container #########################################

  mysql:
    image: abenevaut/laradock-mysql:0.1.2
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - TZ=${DOCKER_PROJECT_TZ}
    volumes:
      - ./laradock/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${DOCKER_STORAGE_PATH}/mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend

  ### Redis Container #########################################

  redis:
    image: abenevaut/laradock-redis:0.1.2
    volumes:
      - ${DOCKER_STORAGE_PATH}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  ### Mailhog Container #########################################

  mailhog:
    image: abenevaut/laradock-mailhog:0.1.2
    ports:
      - "${MAIL_PORT}:1025"
      - "${DOCKER_MAILHOG_PUBLIC_HTTP_PORT}:8025"
    networks:
      - backend
      - frontend

  ### ElasticSearch ########################################

  elasticsearch:
    image: abenevaut/laradock-elasticsearch:0.1.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${SCOUT_ELASTIC_PORT}:9200"
      - "${DOCKER_ELASTICSEARCH_PUBLIC_NODE_PORT}:9300"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  ### Kibana ##############################################

  kibana:
    image: abenevaut/laradock-kibana:0.1.2
    ports:
      - "${DOCKER_KIBANA_PUBLIC_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - frontend
      - backend
