name: www

on:
  push:
    branches: [ master ]
    paths:
      - 'www/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'www/**'

defaults:
  run:
    working-directory: ./www

jobs:

  codestyle-phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.4 ]
    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: actions/cache@v2
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php-version }}-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: pecl
          extensions: gd, imagick
      - if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist --no-suggest
      - run: |
          vendor/bin/phpcs --standard=PSR12 app
          vendor/bin/phpcs --standard=PSR12 database/factories
          vendor/bin/phpcs --standard=PSR12 routes
          vendor/bin/phpcs --standard=PSR12 tests --extensions=php

  codestyle-phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.4 ]
    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: actions/cache@v2
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php-version }}-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: pecl
          extensions: gd, imagick
      - if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist --no-suggest
      - run: |
          vendor/bin/phpstan analyse

  tests-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-nodejs_${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-nodejs_${{ matrix.node-version }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run dev
          npm test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ABENEVAUT_GITHUB_TOKEN }}
          MIX_APP_ENV: github-ci
          MIX_APP_DEBUG: true
          MIX_APP_TAG: github-ci
          MIX_PUSHER_APP_ID: ${{ secrets.DEV_PUSHER_APP_ID }}
          MIX_PUSHER_APP_KEY: ${{ secrets.DEV_PUSHER_APP_KEY }}
          MIX_PUSHER_APP_SECRET: ${{ secrets.DEV_PUSHER_APP_SECRET }}
          MIX_PUSHER_APP_CLUSTER: ${{ secrets.PROD_PUSHER_APP_CLUSTER }}
          MIX_SENTRY_PUBLIC_DSN: ${{ secrets.PROD_SENTRY_PUBLIC_DSN }}
      - if: ${{ matrix.node-version == '14.x'}}
        run: bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  tests-php:
    needs: [ codestyle-phpcs, codestyle-phpstan, tests-js ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
        php-version: [ 7.4 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php-version }}-
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-nodejs_${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-nodejs_${{ matrix.node-version }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ABENEVAUT_GITHUB_TOKEN }}
          MIX_APP_ENV: github-ci
          MIX_APP_DEBUG: true
          MIX_APP_TAG: github-ci
          MIX_PUSHER_APP_ID: ${{ secrets.DEV_PUSHER_APP_ID }}
          MIX_PUSHER_APP_KEY: ${{ secrets.DEV_PUSHER_APP_KEY }}
          MIX_PUSHER_APP_SECRET: ${{ secrets.DEV_PUSHER_APP_SECRET }}
          MIX_PUSHER_APP_CLUSTER: ${{ secrets.PROD_PUSHER_APP_CLUSTER }}
          MIX_SENTRY_PUBLIC_DSN: ${{ secrets.PROD_SENTRY_PUBLIC_DSN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: pecl
          extensions: gd, imagick
      - if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist --no-suggest
      - run: |
          cp .env.example .env
          php artisan key:generate
          vendor/bin/paratest
          php artisan config:cache
          php artisan route:cache
          php artisan view:clear
        env:
          MOLLIE_KEY: ${{ secrets.DEV_MOLLIE_KEY }}
      - if: ${{ matrix.php-version == '7.4' }}
        run: bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
