name: www.pokemon-friends.com

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]
  release:
    types: [ published ]

jobs:

  codestyle-phpcs:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.3]

    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: actions/cache@v2
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php-version }}-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: pecl
          extensions: gd, imagick
      - if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist --no-suggest
      - run: vendor/bin/phpcs --standard=PSR12 app
      - run: vendor/bin/phpcs --standard=PSR12 components
      - run: vendor/bin/phpcs --standard=PSR12 database/factories
      - run: vendor/bin/phpcs --standard=PSR12 routes
      - run: vendor/bin/phpcs --standard=PSR12 tests --extensions=php

  codestyle-phpstan:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.3]

    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: actions/cache@v2
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php-version }}-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: pecl
          extensions: gd, imagick
      - if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist --no-suggest
      - run: vendor/bin/phpstan analyse -l 0 app components tests

  tests-js:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-nodejs_${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-nodejs_${{ matrix.node-version }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ABENEVAUT_GITHUB_TOKEN }}
      - run: npm run dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ABENEVAUT_GITHUB_TOKEN }}
          MIX_PUSHER_APP_ID: ${{ secrets.DEV_PUSHER_APP_ID }}
          MIX_PUSHER_APP_KEY: ${{ secrets.DEV_PUSHER_APP_KEY }}
          MIX_PUSHER_APP_SECRET: ${{ secrets.DEV_PUSHER_APP_SECRET }}
      - run: npm test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ABENEVAUT_GITHUB_TOKEN }}
          MIX_PUSHER_APP_ID: ${{ secrets.DEV_PUSHER_APP_ID }}
          MIX_PUSHER_APP_KEY: ${{ secrets.DEV_PUSHER_APP_KEY }}
          MIX_PUSHER_APP_SECRET: ${{ secrets.DEV_PUSHER_APP_SECRET }}
      - if: ${{ matrix.node-version == '12.x'}}
        run: bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info

  tests-php:

    needs: [codestyle-phpcs, codestyle-phpstan, tests-js]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        php-version: [7.3]

    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - uses: actions/cache@v2
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php-version }}-
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-nodejs_${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-nodejs_${{ matrix.node-version }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ABENEVAUT_GITHUB_TOKEN }}
          MIX_PUSHER_APP_ID: ${{ secrets.DEV_PUSHER_APP_ID }}
          MIX_PUSHER_APP_KEY: ${{ secrets.DEV_PUSHER_APP_KEY }}
          MIX_PUSHER_APP_SECRET: ${{ secrets.DEV_PUSHER_APP_SECRET }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: pecl
          extensions: gd, imagick
      - if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist --no-suggest
      - run: cp .env.example .env
      - run: php artisan key:generate
        env:
          MOLLIE_KEY: ${{ secrets.MOLLIE_KEY }}
      - run: vendor/bin/phpunit
        env:
          MOLLIE_KEY: ${{ secrets.MOLLIE_KEY }}
      - if: ${{ matrix.node-version == '12.x'}}
        run: bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml

  deploy:

    needs: [tests-js, tests-php]

    runs-on: ubuntu-latest

    if: contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_12.x-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com
      - run: npm install
      - run: npm run prod
      - uses: actions/cache@v2
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php-version }}-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          coverage: xdebug
          tools: pecl
          extensions: gd, imagick
      - if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist --no-suggest
      - run: php artisan elfinder:publish
      - run: php artisan asset-cdn:sync --env=production
        env:
          OBJECT_STORAGE_KEY: ${{ secrets.OBJECT_STORAGE_KEY }}
          OBJECT_STORAGE_SECRET: ${{ secrets.OBJECT_STORAGE_SECRET }}
          OBJECT_STORAGE_REGION: ${{ secrets.OBJECT_STORAGE_REGION }}
          OBJECT_STORAGE_BUCKET: ${{ secrets.OBJECT_STORAGE_BUCKET }}
          OBJECT_STORAGE_SERVER: ${{ secrets.OBJECT_STORAGE_SERVER }}
          OBJECT_STORAGE_URL: ${{ secrets.OBJECT_STORAGE_URL }}
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY_FORTRABBIT }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: pre-deploy
        uses: appleboy/ssh-action@master
        with:
          host: deploy.eu2.frbit.com
          username: pkmn-friends
          key: ${{ secrets.PRIVATE_KEY_FORTRABBIT}}
          script: |
            php artisan config:clear
            php artisan route:clear
      - name: deploy
        run: |
          git config --global user.email "deploy@pokemon-friends.com"
          git config --global user.name "deploy-pkmn-friends"
          git remote add fortrabbit pkmn-friends@deploy.eu2.frbit.com:pkmn-friends.git
          git push fortrabbit master
      - name: post-deploy
        uses: appleboy/ssh-action@master
        with:
          host: deploy.eu2.frbit.com
          username: pkmn-friends
          key: ${{ secrets.PRIVATE_KEY_FORTRABBIT}}
          script: |
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear
            php artisan migrate --force
